---

#- debug:  var=nvm
#- debug:  var=ansible_env

- name:   Install the selected node version
  become: true
  shell:  "bash -c '. {{ansible_env.NVM_SCRIPT}}; nvm install {{nvm.ver}}'"

- name:   Set the default alias
  become: true
  shell:  "bash -c '. {{ansible_env.NVM_SCRIPT}}; nvm alias default {{nvm.ver}}'"

- name: Set Permissions
  become: true
  file:
    path: "{{ nvm_path }}/versions/{{nvm.type}}/v{{nvm.ver}}"
    state: directory
    mode: 0775
    owner: root
    group: "{{nvm_group}}"
    recurse: true

- name:   Link the executable files for all users
  become: true
  file:
    src:  "{{ nvm_path }}/versions/{{nvm.type}}/v{{nvm.ver}}/bin/{{ item }}"
    dest: "/usr/local/bin/{{ item }}"
    state: link
    force: true
  with_items: "{{execs}}"

