---

- name: Ensure Required Items
  fail: 
    msg: "Please ensure '{{ item.str }}' is set to a valid path"
  when:
    - not item.path is defined or item.path == ""
  with_items:
    - { path: '{{ nvm_script }}', str: 'nvm_script' }

- name: Install the selected node version
  shell:  |
    . {{ nvm_script }}
    nvm install {{ nvm.ver }}
    nvm alias default {{ nvm.ver }}
  become: true

- name: Set Permissions
  file:
    path: "{{ nvm_path }}/versions/{{nvm.type}}/{{nvm.ver}}"
    state: directory
    mode: 0775
    owner: root
    group: "{{ nvm_group }}"
    recurse: true
  become: true

