---

- name: Add required packages
  become: true
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - build-essential
    - git
    - openssl
    - libssl-dev
    - curl

- name: Clone nvm into place
  shell: git clone https://github.com/creationix/nvm.git {{nvm_install_dir}}
  args:
    creates: "{{nvm_install_dir}}/nvm.sh"
  become: true
#  when: nvm_stat.stat.exists != true

- name: Make global directories
  become: true
  file:
    path: "{{item}}"
    state: directory
    mode: 0775
    owner: root
    group: admin
  with_items:
    - "{{node_path}}"
    - "{{nvm_path}}"

- name: Add required lines to /etc/environment
  become: true
  blockinfile:
    dest: "/etc/environment"
    block: |
      export NVM_DIR={{nvm_path}}
      #export NPM_CONFIG_PREFIX={{node_path}}
      export NODE_PATH={{node_path}}
      export NVM_SCRIPT={{nvm_install_dir}}/nvm.sh
      source {{nvm_install_dir}}/nvm.sh
    marker: "# {mark} ANSIBLE MANAGED BLOCK - NVM"
    insertbefore: EOL

- name: Update path variable in /etc/environment
  become: true
  lineinfile:
    dest: /etc/environment
    state: present
    regexp: '^PATH="{{node_path}}/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games"'
    line: 'PATH="{{node_path}}/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games"'

- name: Add /etc/profile.d/nvm.sh
  become: true
  template:
    src: ../templates/nvm.sh.j2
    dest: /etc/profile.d/nvm.sh
    mode: 0644
    owner: root
    group: root

