---

- name: Install required system packages
  become: true
  apt:
    name: [ 'build-essential', 'git', 'openssl', 'libssl-dev', 'curl' ]
    state: present

- name: Remove node package, in lieu of nvm
  become: true
  apt:
    name: [ 'nodejs', 'node' ]
    state: absent

- name: Ensure the nvm group exists
  group:
    name: "{{ nvm_group }}"
    state: present

- name: Append the nvm group to users
  user:
    name: "{{ item }}"
    groups: "{{ nvm_group }}"
    append: yes
  with_items:
    - "{{ generic_user.username }}"
    - "{{ ansible_user }}"
  become: true

- name: Make global directories
  become: true
  file:
    path: "{{ item }}"
    state: directory
    mode: 0775
    owner: root
    group: "{{ nvm_group }}"
    recurse: true
  with_items:
    - "{{ node_path }}"
    - "{{ nvm_path }}"

- name: Make global directories inherit
  become: true
  file:
    path: "{{ item }}"
    mode: "g+s"
    owner: root
    group: "{{ nvm_group }}"
  with_items:
    - "{{ node_path }}"
    - "{{ nvm_path }}"

- name: Link the global .nvm folder '{{ nvm_path }}' to the ansible user's home directory
  file:
    src:  "{{ nvm_path }}"
    dest: "/home/{{ ansible_user }}/.nvm"
    state: link

- name: Add required lines to /etc/environment
  become: true
  blockinfile:
    dest: "/etc/environment"
    block: |
      export NVM_DIR={{ nvm_path }}
      export NODE_PATH={{ node_path }}
      export NVM_SCRIPT={{ nvm_script }}
    marker: "# {mark} ANSIBLE MANAGED BLOCK - NVM"
    insertbefore: EOL

- name: Clone nvm into place
  shell: git clone https://github.com/creationix/nvm.git {{ nvm_install_dir }}
  args:
    creates: "{{ nvm_install_dir }}/nvm.sh"
  become: true
#  when: nvm_stat.stat.exists != true

- name: Add /etc/profile.d/nvm.sh
  become: true
  template:
    src: ../templates/nvm.sh.j2
    dest: /etc/profile.d/nvm.sh
    mode: 0644
    owner: root
    group: root

- name: Remove remnant pm2 folders
  become: true
  file:
    state: absent
    dest: "{{ item }}"
  with_items:
    - /usr/lib/node_modules

- name: Remove remnant global pm2 links
  become: true
  file:
    state: absent
    dest: "/usr/bin/{{ item }}"
  with_items: "{{apt_pkgs}}"

