---

- include: ./init.yml
  when: do_init == true
  tags: [ 'init' ]

- include: ./configure.yml
  when: do_configure == true
  tags: [ 'init', 'configure' ]

- include: ./port_enable.yml
  when: (do_configure == true) and (vm_client_type == 'gui')
  tags: [ 'init', 'configure' ]
