---

- include_tasks: ./prep.yml

- include_tasks: ./proc_stop.yml
  when: ((['init', 'processes'] | intersect(flags)) | length > 0)

- include_tasks: ./init.yml
  when: ((['init'] | intersect(flags)) | length > 0)

- include_tasks: ./configure.yml
  when: ((['configure'] | intersect(flags)) | length > 0)

- include_tasks: ./port_enable.yml
  when: ((['configure', 'port_enable'] | intersect(flags)) | length > 0) and vm_client_type == 'gui'

- include_tasks: ./package_local_wipe.yml
  when: ((['wipe'] | intersect(flags)) | length > 0)

- include_tasks: ./package_global_install.yml
  when: ((['configure'] | intersect(flags)) | length > 0)

- include_tasks: ./package_global_upgrade.yml
  when: ((['upgrade'] | intersect(flags)) | length > 0)

- include_tasks: ./package_local_install.yml
  when: ((['configure'] | intersect(flags)) | length > 0)

- include_tasks: ./package_local_upgrade.yml
  when: ((['upgrade'] | intersect(flags)) | length > 0)

- include_tasks: ./proc_stop.yml
  when: ((['restart', 'processes', 'upgrade'] | intersect(flags)) | length > 0) and (deploy_dir is defined and deploy_dir != '')

- include_tasks: ./proc_start.yml
  when: ((['restart', 'processes', 'upgrade'] | intersect(flags)) | length > 0) and (deploy_dir is defined and deploy_dir != '')

- include_tasks: ./proc_auto_start.yml
  when: ((['processes', 'upgrade'] | intersect(flags)) | length > 0) and (deploy_dir is defined and deploy_dir != '')

