---

- name: Test Paths
  include_tasks: test_paths.yml
  when: ((['restart', 'processes', 'upgrade', 'restart'] | intersect(flags)) | length > 0)

- name: Initial Preparations
  include_tasks: prep.yml

- name: Stop the processes
  include_tasks: proc_stop.yml
  when: ((['init', 'processes'] | intersect(flags)) | length > 0)

- name: Set Node Version from NVM
  include_tasks: set_node_version.yml
  when: ((['init', 'configure', 'upgrade', 'version'] | intersect(flags)) | length > 0)

- name: Initialize
  include_tasks: init.yml
  when: ((['init'] | intersect(flags)) | length > 0)

- name: Configure
  include_tasks: configure.yml
  when: ((['configure'] | intersect(flags)) | length > 0)

- name: Enable Ports
  include_tasks: port_enable.yml
  when: ((['configure', 'port_enable'] | intersect(flags)) | length > 0) and vm_client_type == 'gui'

- name: Wipe local packages
  include_tasks: package_local_wipe.yml
  when: ((['wipe'] | intersect(flags)) | length > 0)

- name: Global install
  include_tasks: package_global_install.yml
  when: ((['configure'] | intersect(flags)) | length > 0)

- name: Global upgrade
  include_tasks: package_global_upgrade.yml
  when: ((['upgrade'] | intersect(flags)) | length > 0)

- name: Local install
  include_tasks: package_local_install.yml
  when: ((['configure'] | intersect(flags)) | length > 0)

- name: Local upgrade
  include_tasks: package_local_upgrade.yml
  when: ((['upgrade'] | intersect(flags)) | length > 0)

- name: Stop processes
  include_tasks: proc_stop.yml
  when: ((['restart', 'processes', 'upgrade'] | intersect(flags)) | length > 0)

- name: Start Processes
  include_tasks: proc_start.yml
  when: ((['restart', 'processes', 'upgrade'] | intersect(flags)) | length > 0)

- name: Set Auto Start
  include_tasks: proc_auto_start.yml
  when: ((['processes', 'upgrade'] | intersect(flags)) | length > 0)

- name: Cleanup
  include_tasks: cleanup.yml
  tags: ['all']

