---

- include: ./prep.yml
  tags: [ 'always' ]

- include: ./proc_stop.yml
  tags: ['init', 'configure', 'upgrade', 'packages', 'pm2' ]

- include: ./init.yml
  when: "'init' in flags"
  tags: [ 'init' ]

- include: ./configure.yml
  when: "'configure' in flags"
  tags: [ 'configure' ]

- include: ./port_enable.yml
  when: "'configure' in flags and vm_client_type == 'gui'"
  tags: [ 'configure' ]

- include: ./package_install.yml
  when: "'packages' in flags"
  tags: [ 'configure', 'packages' ]

- include: ./package_upgrade.yml
  when: "'packages' in flags"
  tags: [ 'upgrade', 'packages' ]

- include: ./proc_stop.yml
  tags: ['init', 'configure', 'upgrade', 'packages', 'pm2' ]
  when: deploy_dir is defined and deploy_dir != ''

- include: ./proc_start.yml
  tags: ['init', 'configure', 'upgrade', 'packages', 'pm2' ]
  when: deploy_dir is defined and deploy_dir != ''

- include: ./proc_auto_start.yml
  tags: ['configure', 'upgrade', 'packages', 'pm2' ]
  when: deploy_dir is defined and deploy_dir != ''

