---

- include: ./prep.yml
  tags: [ 'always' ]

- name: Get pm2 location
  shell: which pm2
  tags: [ 'always' ]
  failed_when: pm2.rc > 1
  register: pm2

- name: Ensure pm2 is not running
  shell: "pm2 kill"
  become: false
  tags: ['init', 'configure', 'upgrade', 'packages' ]
  when: pm2.stdout != ''

- include: ./init.yml
  when: "'init' in flags"
  tags: [ 'init' ]

- include: ./configure.yml
  when: "'configure' in flags"
  tags: [ 'configure' ]

- include: ./port_enable.yml
  when: "'configure' in flags and vm_client_type == 'gui'"
  tags: [ 'configure' ]

- include: ./packages.yml
  when: "'packages' in flags"
  tags: [ 'always' ]

- name: Stop Server
  shell: "npm stop"
  args:
    chdir: "{{ deploy_dir }}"
  register: pm2
  failed_when: pm2.rc > 1
  tags: ['init', 'configure', 'upgrade', 'packages' ]
  when: deploy_dir is defined and deploy_dir != ''

- name: Start server
  shell: "npm start"
  args:
    chdir: "{{ deploy_dir }}"
  tags: ['init', 'configure', 'upgrade', 'packages' ]
  when: deploy_dir is defined and deploy_dir != ''

