---

- debug: var=flags
  tags: [ 'always' ]

- include: ./init.yml
  when: "'init' in flags"
  tags: [ 'init' ]

- include: ./configure.yml
  when: "'configure' in flags"
  tags: [ 'configure' ]

- include: ./port_enable.yml
  when: "'configure' in flags and (vm_client_type == 'gui')"
  tags: [ 'configure' ]

- include: ./packages.yml
  when: "'packages' in flags"
