---

- name: Install NPM global packages
  become: true
  shell: |
    . {{ nvm_script }}
    npm install -g {{npm_pkgs|join(' ')}} --quiet --silent

- name: Install PM2 modules
  shell: |
    . {{ nvm_script }}
    pm2 install {{pm2_mods|join(' ')}}
  args:
    chdir: "{{ remote_deploy_dir }}"
  when:
    - pm2_mods | length > 0
    - PM2_PATH != ''
  become: true
  become_user: '{{ generic_user.username }}'