---

# - name: Reboot the server
#   include_role:
#     name: pgkehle.restart

- include_tasks: ./proc_stop.yml
- include_tasks: ./proc_start.yml

#   shell: pm2 startup
#   shell: pm2 startup ubuntu -u {{ target_user }} --hp {{ remote_deploy_dir }}
#   shell: pm2 startup systemd -u {{ target_user }} --hp {{ remote_deploy_dir }}

- name: Set PM2 to start on reboot
  shell: |
    . {{ nvm_script }}
    pm2 startup ubuntu -u vm_user --hp '/home/{{target_user}}'
  become: true

- name: Save PM2
  shell: pm2 save
  become: true
  become_user: '{{ target_user }}'

