---

- name: Stop PM2 Process(es)
  shell: |
    . {{ nvm_script }}
    pm2 stop all
  register: res
  failed_when: res.rc > 1
  when:
    - PM2_PATH != ''
  become: true
  become_user: '{{ generic_user.username }}'