---

- name: Get pm2 location
  shell: which pm2
  failed_when: pm2_loc.rc > 1
  register: pm2_loc

- name: Stop Node Process(es)
  shell: "npm stop"
  args:
    chdir: "{{ deploy_dir }}"
  register: npm_stop
  failed_when: npm_stop.rc > 1
  when: deploy_dir is defined and deploy_dir != ''

- name: kill tunnels
  shell: ps -ef | grep 'ssh -NL' | grep -v grep | awk '{print $2}' | xargs kill -9
  when: ((vm_client_type == 'worker') or (vm_client_type == 'scheduler'))

