---

- name: Start PM2 Process(es)
  shell: |
    . {{ nvm_script }}
    pm2 start ecosystem.yml
  args:
    chdir: "{{ remote_base_dir }}"
  when:
    - PM2_PATH != ''
  become: true
  become_user: '{{ generic_user.username }}'