---

- name: Set NVM_BIN when nvm is installed
  set_fact:
    NVM_BIN: "{{ lookup('env', 'NVM_DIR') }}/versions/{{ nvm.type }}/{{ nvm.ver }}/bin"
  when: lookup('env', 'NVM_DIR') is defined

- name: Get npm path
  shell: which npm
  become: true
  register: results_npm
  failed_when: results_npm.rc > 1
  changed_when: false

- name: Get pm2 path
  shell: which pm2
  become: true
  register: results_pm2
  failed_when: results_pm2.rc > 1
  changed_when: false

- name: Set npm exec path
  set_fact: 
    NPM_PATH: "{{ results_npm.stdout }}"

- name: Set pm2 exec path
  set_fact: 
    PM2_PATH: "{{ results_pm2.stdout }}"

- name: debugging
  debug: 
    var: "{{ item }}"
  with_items:
    - NPM_PATH
    - PM2_PATH
